// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT5LbqgF_McuLQ42bj6Ff-D8kwxSGUj3g',
    appId: '1:401981331882:web:eaddb12fa4e80b397eb3d3',
    messagingSenderId: '401981331882',
    projectId: 'chat-1a4d9',
    authDomain: 'chat-1a4d9.firebaseapp.com',
    storageBucket: 'chat-1a4d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4lk093rVIRWhxxNBgoqTrzchbp8olMEs',
    appId: '1:401981331882:android:b4dcb368a6054ea17eb3d3',
    messagingSenderId: '401981331882',
    projectId: 'chat-1a4d9',
    storageBucket: 'chat-1a4d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwdgHAeFc0GWazzqJeH_5L9fQQvltPq_A',
    appId: '1:401981331882:ios:9b39e3a597dd096e7eb3d3',
    messagingSenderId: '401981331882',
    projectId: 'chat-1a4d9',
    storageBucket: 'chat-1a4d9.firebasestorage.app',
    iosBundleId: 'com.example.secureChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwdgHAeFc0GWazzqJeH_5L9fQQvltPq_A',
    appId: '1:401981331882:ios:9b39e3a597dd096e7eb3d3',
    messagingSenderId: '401981331882',
    projectId: 'chat-1a4d9',
    storageBucket: 'chat-1a4d9.firebasestorage.app',
    iosBundleId: 'com.example.secureChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT5LbqgF_McuLQ42bj6Ff-D8kwxSGUj3g',
    appId: '1:401981331882:web:87084f8cbbe8d1a57eb3d3',
    messagingSenderId: '401981331882',
    projectId: 'chat-1a4d9',
    authDomain: 'chat-1a4d9.firebaseapp.com',
    storageBucket: 'chat-1a4d9.firebasestorage.app',
  );
}
